"""empty message

Revision ID: 5f5df1d62d98
Revises: b987be2c784e
Create Date: 2022-05-10 15:07:07.962741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5df1d62d98'
down_revision = 'b987be2c784e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('base_experience', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('ability_name', sa.String(), nullable=True))
    op.drop_column('pokemon', 'base_exp')
    op.drop_column('pokemon', 'ability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pokemon', sa.Column('base_exp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pokemon', 'ability_name')
    op.drop_column('pokemon', 'base_experience')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
